### ISSUE TITLE
Question: Remote SSH tasks

### ISSUE THREAD

**Issue by richardbporter** [taskphp/task#8]
Hi - I'm looking at a few different PHP task runners right now: bldr, robo, Rocketeer - Are there plans for TaskPHP to include a remote SSH command task? Or maybe I overlooked something, Is this possible right now?

Thanks!

**Comment by mbfisher** [comment]
Hi!

There isn't a remote command plugin in the `Task` vendor namespace, and to my knowledge there aren't any third party implementations.

However, plugins are just PHP code so if you know of a library which can execute SSH commands it would be trivial to include it in your tasks.

I've been asked about remote command plugins a few times now, should probably be next on the list!

M

**Comment by richardbporter** [comment]
Cool, gotcha. I was looking at https://github.com/Herzult/php-ssh as a possibility. 

Anyway, thanks again.
